#!/bin/bash
# Make Electron apps that bundle their own Electron run natively on Wayland.
# (Apps using Arch's system electronXX already read ~/.config/electron-flags.conf.)
#
# For each app this creates:
#   /usr/local/bin/<name>                            wrapper passing ~/.config/electron-flags.conf
#   ~/.local/share/applications/<name>.desktop       launcher entry pointing at the wrapper

# name:real_binary:desktop_file
APPS=(
    "discord:/usr/bin/discord:discord.desktop"
    "postman:/opt/postman/Postman:postman.desktop"
)

for app in "${APPS[@]}"; do
    IFS=: read -r name bin desktop <<< "$app"

    if [ ! -x "$bin" ]; then
        echo "electron-wayland: skipping $name ($bin not installed)"
        continue
    fi

    sudo tee "/usr/local/bin/$name" >/dev/null <<EOF
#!/bin/bash
# Generated by dots-hyprland/scripts/electron-wayland.sh
flags=()
flags_file="\${XDG_CONFIG_HOME:-\$HOME/.config}/electron-flags.conf"
if [[ -f "\$flags_file" ]]; then
    while IFS= read -r line; do
        [[ -n "\$line" && ! "\$line" =~ ^[[:space:]]*# ]] && flags+=("\$line")
    done < "\$flags_file"
fi
exec "$bin" "\${flags[@]}" "\$@"
EOF
    sudo chmod 755 "/usr/local/bin/$name"

    if [ -f "/usr/share/applications/$desktop" ]; then
        mkdir -p ~/.local/share/applications
        sed "s|^Exec=[^ ]*|Exec=/usr/local/bin/$name|" \
            "/usr/share/applications/$desktop" > ~/.local/share/applications/"$desktop"
    fi
done

update-desktop-database ~/.local/share/applications 2>/dev/null || true
